# credit: https://github.com/istvano/ansible_role_microk8s
- name: microk8s
  hosts: all
  gather_facts: False
  vars:
    rcpath: "/home/{{ansible_user}}/.bashrc"
  tasks:
    - name: shellrc
      blockinfile:
        path: "{{ rcpath }}"
        block: |
          export EDITOR=vim
        state: present
        create: true
    - name: etc_hosts
      blockinfile:
        path: "/etc/hosts"
        block: |
          {{registry_localdomain_ip_addr}} registry.localdomain
        state: present
        create: true
      become: true
    - name: timezone
      become: true
      community.general.timezone:
        name: "{{timezone}}"
