# credit: https://github.com/istvano/ansible_role_microk8s
- name: microk8s
  hosts: all
  gather_facts: False
  vars:
    rcpath: "/home/{{ansible_user}}/.bashrc"
  tasks:
    - name: shellrc
      blockinfile:
        path: "{{ rcpath }}"
        block: |
          export EDITOR=vim
          export PS1='[\t]:(\u@\h):[\W] $ '
        state: present
        create: true
    - name: /etc/hosts registry.localdomain
      blockinfile:
        path: "/etc/hosts"
        block: |
          {{registry_localdomain_ip_addr}} registry.localdomain
        state: present
        create: true
      become: true
    - name: timezone
      become: true
      community.general.timezone:
        name: "{{timezone}}"
    - name: static ip
      block:
        - name: config
          copy:
            dest: "/etc/netplan/01-netcfg.yaml"
            content: |
              network:
                version: 2
                renderer: networkd
                ethernets:
                  {{static_ip.iface}}:
                    dhcp4: no
                    addresses:
                      - {{static_ip.addr}}/24
                    routes:
                      - to: default
                        via: {{static_ip.route}}
                    nameservers:
                      addresses: {{static_ip.nameservers|replace("'","")|replace(' ','') }}
        - name: apply
          command:
            cmd: "netplan apply"
      when: static_ip is defined
      become: yes
    - name: hostname
      ansible.builtin.hostname:
        name: "{{inventory_hostname_short}}"
      become: true
    - name: /etc/hosts hostname
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ ansible_host }}"
        line: "{{ ansible_host }} {{ inventory_hostname }} {{ ansible_hostname }}"
        state: present
      become: true
